"""initial migration

Revision ID: 0feb1b5975fc
Revises: 
Create Date: 2025-02-03 19:13:46.353797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0feb1b5975fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_name', sa.String(length=100), nullable=False),
    sa.Column('target_amount', sa.Float(), nullable=False),
    sa.Column('current_amount', sa.Float(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('goals')
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        #batch_op.drop_constraint('transaction_goal_id_fkey', type_='foreignkey')
        batch_op.drop_column('goal_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('transaction_goal_id_fkey', 'goals', ['goal_id'], ['id'])

    op.create_table('goals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('goal_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('target_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('current_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('deadline', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], name='goal_category_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='goal_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='goal_pkey')
    )
    op.drop_table('goal')
    # ### end Alembic commands ###
